export default [
  {
    id: "rebelalliance-asf01bwing",
    title: "A/SF-01 B-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "ASF01BWING",
      "BLADE SQUADRON VETERAN",
      "BLADE SQUADRON VETERAN",
      "BLADE SQUADRON VETERAN",
      "BLADE SQUADRON VETERAN",
      "BLUE SQUADRON PILOT",
      "BLUE SQUADRON PILOT",
      "BLUE SQUADRON PILOT",
      "BLUE SQUADRON PILOT",
      "BRAYLEN STRAMM",
      "BRAYLEN STRAMM",
      "TEN NUMB",
      "TEN NUMB",
      "GINA MOONSONG",
      "HERA SYNDULLA",
      "NETREM POLLARD",
    ],
  },
  {
    id: "rebelalliance-arc170starfighter",
    title: "ARC-170 STARFIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "ARC170STARFIGHTER",
      "GARVEN DREIS",
      "IBTISAM",
      "NORRA WEXLEY",
      "SHARA BEY",
    ],
  },
  {
    id: "rebelalliance-attackshuttle",
    title: "ATTACK SHUTTLE",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "ATTACKSHUTTLE",
      "“ZEB” ORRELIOS",
      "EZRA BRIDGER",
      "HERA SYNDULLA",
      "SABINE WREN",
    ],
  },
  {
    id: "rebelalliance-auzituckgunship",
    title: "AUZITUCK GUNSHIP",
    category: ["SHIP", "REBELALLIANCE"],
    tags: ["AUZITUCKGUNSHIP", "KASHYYYK DEFENDER", "LOWHHRICK", "WULLFFWARRO"],
  },
  {
    id: "rebelalliance-btla4ywing",
    title: "BTL-A4 Y-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "BTLA4YWING",
      "“DUTCH” VANDER",
      "EVAAN VERLAINE",
      "GOLD SQUADRON VETERAN",
      "GRAY SQUADRON BOMBER",
      "HORTON SALM",
      "NORRA WEXLEY",
    ],
  },
  {
    id: "rebelalliance-btls8kwing",
    title: "BTL-S8 K-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "BTLS8KWING",
      "ESEGE TUKETU",
      "MIRANDA DONI",
      "WARDEN SQUADRON PILOT",
    ],
  },
  {
    id: "rebelalliance-cr90corelliancorvette",
    title: "CR90 CORELLIAN CORVETTE",
    category: ["SHIP", "REBELALLIANCE"],
    tags: ["CR90CORELLIANCORVETTE", "ALDERAANIAN GUARD", "ALDERAANIAN GUARD"],
  },
  {
    id: "rebelalliance-ewing",
    title: "E-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "EWING",
      "CORRAN HORN",
      "GAVIN DARKLIGHTER",
      "KNAVE SQUADRON ESCORT",
      "ROGUE SQUADRON ESCORT",
    ],
  },
  {
    id: "rebelalliance-fangfighter",
    title: "FANG FIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "FANGFIGHTER",
      "FENN RAU",
      "FENN RAU",
      "BODICA VENJ",
      "BODICA VENJ",
      "DIRK ULLODIN",
      "DIRK ULLODIN",
      "CLAN WREN VOLUNTEER",
      "CLAN WREN VOLUNTEER",
    ],
  },
  {
    id: "rebelalliance-gauntletfighter",
    title: "GAUNTLETFIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "GAUNTLETFIGHTER",
      "CHOPPER-GAUNTLETFIGHTER",
      "EZRABRIDGER-GAUNTLETFIGHTER",
      "MANDALORIANRESISTANCEPILOT",
    ],
  },
  {
    id: "rebelalliance-gr75mediumtransport",
    title: "GR-75 MEDIUM TRANSPORT",
    category: ["SHIP", "REBELALLIANCE"],
    tags: ["GR75MEDIUMTRANSPORT", "ECHO BASE EVACUEES", "ECHO BASE EVACUEES"],
  },
  {
    id: "rebelalliance-hwk290lightfreighter",
    title: "HWK-290 LIGHT FREIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "HWK290LIGHTFREIGHTER",
      "JAN ORS",
      "KYLE KATARN",
      "REBEL SCOUT",
      "ROARK GARNET",
    ],
  },
  {
    id: "rebelalliance-modifiedyt1300lightfreighter",
    title: "MODIFIED YT-1300 LIGHT FREIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "MODIFIEDYT1300LIGHTFREIGHTER",
      "CHEWBACCA",
      "CHEWBACCA",
      "HAN SOLO",
      "HAN SOLO",
      "LANDO CALRISSIAN",
      "LANDO CALRISSIAN",
      "OUTER RIM SMUGGLER",
      "OUTER RIM SMUGGLER",
      "OUTER RIM SMUGGLER",
      "LEIA ORGANA",
    ],
  },
  {
    id: "rebelalliance-rz1awing",
    title: "RZ-1 A-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "RZ1AWING",
      "ARVEL CRYNYD",
      "ARVEL CRYNYD",
      "GREEN SQUADRON PILOT",
      "GREEN SQUADRON PILOT",
      "GREEN SQUADRON PILOT",
      "JAKE FARRELL",
      "JAKE FARRELL",
      "PHOENIX SQUADRON PILOT",
      "PHOENIX SQUADRON PILOT",
      "PHOENIX SQUADRON PILOT",
      "PHOENIX SQUADRON PILOT",
      "PHOENIX SQUADRON PILOT",
      "PHOENIX SQUADRON PILOT",
      "WEDGE ANTILLES",
      "SABINE WREN",
      "HERA SYNDULLA",
      "AHSOKA TANO",
      "SHARA BEY",
      "DEREK KLIVIAN",
    ],
  },
  {
    id: "rebelalliance-sheathipedeclassshuttle",
    title: "SHEATHIPEDE-CLASS SHUTTLE",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "SHEATHIPEDECLASSSHUTTLE",
      "“ZEB” ORRELIOS",
      "“ZEB” ORRELIOS",
      "AP-5",
      "AP-5",
      "EZRA BRIDGER",
      "EZRA BRIDGER",
      "FENN RAU",
      "FENN RAU",
    ],
  },
  {
    id: "rebelalliance-t65xwing",
    title: "T-65 X-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "T65XWING",
      "BIGGS DARKLIGHTER",
      "BLUE SQUADRON ESCORT",
      "CAVERN ANGELS ZEALOT",
      "EDRIO TWO TUBES",
      "GARVEN DREIS",
      "JEK PORKINS",
      "KULLBEE SPERADO",
      "LEEVAN TENZA",
      "LUKE SKYWALKER",
      "RED SQUADRON VETERAN",
      "THANE KYRELL",
      "THANE KYRELL",
      "WEDGE ANTILLES",
    ],
  },
  {
    id: "rebelalliance-tielnfighter",
    title: "TIE/LN FIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "TIELNFIGHTER",
      "“ZEB” ORRELIOS",
      "CAPTAIN REX",
      "EZRA BRIDGER",
      "SABINE WREN",
    ],
  },
  {
    id: "rebelalliance-ut60duwing",
    title: "UT-60D U-WING",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "UT60DUWING",
      "BENTHIC TWO TUBES",
      "BLUE SQUADRON SCOUT",
      "BODHI ROOK",
      "CASSIAN ANDOR",
      "HEFF TOBBER",
      "MAGVA YARRO",
      "PARTISAN RENEGADE",
      "PARTISAN RENEGADE",
      "SAW GERRERA",
      "K-2SO",
    ],
  },
  {
    id: "rebelalliance-vcx100lightfreighter",
    title: "VCX-100 LIGHT FREIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "VCX100LIGHTFREIGHTER",
      "“CHOPPER”",
      "“CHOPPER”",
      "HERA SYNDULLA",
      "HERA SYNDULLA",
      "KANAN JARRUS",
      "KANAN JARRUS",
      "LOTHAL REBEL",
      "LOTHAL REBEL",
      "LOTHAL REBEL",
      "ALEXSANDR KALLUS",
    ],
  },
  {
    id: "rebelalliance-yt2400lightfreighter",
    title: "YT-2400 LIGHT FREIGHTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "YT2400LIGHTFREIGHTER",
      "“LEEBO”",
      "DASH RENDAR",
      "WILD SPACE FRINGER",
    ],
  },
  {
    id: "rebelalliance-z95af4headhunter",
    title: "Z-95-AF4 HEADHUNTER",
    category: ["SHIP", "REBELALLIANCE"],
    tags: [
      "Z95AF4HEADHUNTER",
      "AIREN CRACKEN",
      "BANDIT SQUADRON PILOT",
      "LIEUTENANT BLOUNT",
      "TALA SQUADRON PILOT",
    ],
  },
  {
    id: "scumandvillainy-aggressorassaultfighter",
    title: "AGGRESSOR ASSAULT FIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: ["AGGRESSORASSAULTFIGHTER", "IG-88A", "IG-88B", "IG-88C", "IG-88D"],
  },
  {
    id: "scumandvillainy-btla4ywing",
    title: "BTL-A4 Y-WING",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "BTLA4YWING",
      "CRYMORAH GOON",
      "DREA RENTHAL",
      "HIRED GUN",
      "KAVIL",
      "LEEMA KAI",
      "ARLIZ HADRASSIAN",
      "AMAXINE WARRIOR",
      "PADRIC",
      "JINATA SECURITY OFFICER",
    ],
  },
  {
    id: "scumandvillainy-croccruiser",
    title: "C-ROC CRUISER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: ["CROCCRUISER", "SYNDICATE SMUGGLERS", "SYNDICATE SMUGGLERS"],
  },
  {
    id: "scumandvillainy-customizedyt1300lightfreighter",
    title: "CUSTOMIZED YT-1300 LIGHT FREIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "CUSTOMIZEDYT1300LIGHTFREIGHTER",
      "FREIGHTER CAPTAIN",
      "HAN SOLO",
      "L3-37'S PROGRAMMING",
      "LANDO CALRISSIAN",
    ],
  },
  {
    id: "scumandvillainy-escapecraft",
    title: "ESCAPE CRAFT",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "ESCAPECRAFT",
      "AUTOPILOT DRONE",
      "L3-37",
      "LANDO CALRISSIAN",
      "OUTER RIM PIONEER",
    ],
  },
  {
    id: "scumandvillainy-fangfighter",
    title: "FANG FIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "FANGFIGHTER",
      "FENN RAU",
      "JOY REKKOFF",
      "KAD SOLUS",
      "OLD TEROCH",
      "SKULL SQUADRON PILOT",
      "SKULL SQUADRON PILOT",
      "ZEALOUS RECRUIT",
      "MANDALORIAN ROYAL GUARD",
      "MANDALORIAN ROYAL GUARD",
      "MANDALORIAN ROYAL GUARD",
      "MANDALORIAN ROYAL GUARD",
    ],
  },
  {
    id: "scumandvillainy-firesprayclasspatrolcraft",
    title: "FIRESPRAY-CLASS PATROL CRAFT",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "FIRESPRAYCLASSPATROLCRAFT",
      "BOBA FETT",
      "BOUNTY HUNTER",
      "EMON AZZAMEEN",
      "KATH SCARLET",
      "KOSHKA FROST",
      "KRASSIS TRELIX",
    ],
  },
  {
    id: "scumandvillainy-g1astarfighter",
    title: "G-1A STARFIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: ["G1ASTARFIGHTER", "4-LOM", "GAND FINDSMAN", "ZUCKUSS"],
  },
  {
    id: "scumandvillainy-gauntletfighter",
    title: "GAUNTLETFIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: ["GAUNTLETFIGHTER", "MAUL", "ROOKKAST", "SHADOWCOLLECTIVEOPERATOR"],
  },
  {
    id: "scumandvillainy-hwk290lightfreighter",
    title: "HWK-290 LIGHT FREIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "HWK290LIGHTFREIGHTER",
      "DACE BONEARM",
      "PALOB GODALHI",
      "SPICE RUNNER",
      "SPICE RUNNER",
      "SPICE RUNNER",
      "TORKIL MUX",
      "GAMUT KEY",
      "KANAN JARRUS",
      "TÁPUSK",
    ],
  },
  {
    id: "scumandvillainy-jumpmaster5000",
    title: "JUMPMASTER 5000",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "JUMPMASTER5000",
      "CONTRACTED SCOUT",
      "CONTRACTED SCOUT",
      "CONTRACTED SCOUT",
      "DENGAR",
      "DENGAR",
      "MANAROO",
      "MANAROO",
      "TEL TREVURA",
      "TEL TREVURA",
      "NOM LUMB",
    ],
  },
  {
    id: "scumandvillainy-kihraxzfighter",
    title: "KIHRAXZ FIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "KIHRAXZFIGHTER",
      "BLACK SUN ACE",
      "CAPTAIN JOSTERO",
      "CARTEL MARAUDER",
      "GRAZ",
      "TALONBANE COBRA",
      "VIKTOR HEL",
    ],
  },
  {
    id: "scumandvillainy-lancerclasspursuitcraft",
    title: "LANCER-CLASS PURSUIT CRAFT",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "LANCERCLASSPURSUITCRAFT",
      "ASAJJ VENTRESS",
      "KETSU ONYO",
      "SABINE WREN",
      "SHADOWPORT HUNTER",
    ],
  },
  {
    id: "scumandvillainy-m12lkimogilafighter",
    title: "M12-L KIMOGILA FIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "M12LKIMOGILAFIGHTER",
      "CARTEL EXECUTIONER",
      "DALAN OBEROS",
      "TORANI KULDA",
    ],
  },
  {
    id: "scumandvillainy-m3ainterceptor",
    title: "M3-A INTERCEPTOR",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "M3AINTERCEPTOR",
      "CARTEL SPACER",
      "CARTEL SPACER",
      "CARTEL SPACER",
      "CARTEL SPACER",
      "GENESIS RED",
      "GENESIS RED",
      "INALDRA",
      "INALDRA",
      "LAETIN A'SHERA",
      "LAETIN A'SHERA",
      "QUINN JAST",
      "QUINN JAST",
      "SERISSU",
      "SERISSU",
      "SUNNY BOUNDER",
      "SUNNY BOUNDER",
      "TANSARII POINT VETERAN",
      "TANSARII POINT VETERAN",
      "TANSARII POINT VETERAN",
      "TANSARII POINT VETERAN",
      "G4R-G0R V/M",
    ],
  },
  {
    id: "scumandvillainy-modifiedtielnfighter",
    title: "MODIFIED TIE/LN FIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "MODIFIEDTIELNFIGHTER",
      "AHHAV",
      "CAPTAIN SEEVOR",
      "FOREMAN PROACH",
      "FOREMAN PROACH",
      "MINING GUILD SURVEYOR",
      "OVERSEER YUSHYN",
      "MINING GUILD SENTRY",
    ],
  },
  {
    id: "scumandvillainy-quadrijettransferspacetug",
    title: "QUADRIJET TRANSFER SPACETUG",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "QUADRIJETTRANSFERSPACETUG",
      "CONSTABLE ZUVIO",
      "JAKKU GUNRUNNER",
      "JAKKU GUNRUNNER",
      "SARCO PLANK",
      "UNKAR PLUTT",
    ],
  },
  {
    id: "scumandvillainy-rogueclassstarfighter",
    title: "ROGUECLASSSTARFIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "ROGUECLASSSTARFIGHTER",
      "CAD BANE",
      "VIKTORHEL-ROGUECLASSSTARFIGHTER",
      "NOMLUMB-ROGUECLASSSTARFIGHTER",
      "OUTERRIMHUNTER",
    ],
  },
  {
    id: "scumandvillainy-scurrgh6bomber",
    title: "SCURRG H-6 BOMBER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: ["SCURRGH6BOMBER", "CAPTAIN NYM", "LOK REVENANT", "SOL SIXXA"],
  },
  {
    id: "scumandvillainy-st70assaultship",
    title: "ST70ASSAULTSHIP",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "ST70ASSAULTSHIP",
      "THEMANDALORIAN",
      "Q90",
      "GUILDBOUNTYHUNTER",
      "OUTERRIMENFORCER",
    ],
  },
  {
    id: "scumandvillainy-starviperclassattackplatform",
    title: "STARVIPER-CLASS ATTACK PLATFORM",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "STARVIPERCLASSATTACKPLATFORM",
      "BLACK SUN ASSASSIN",
      "BLACK SUN ENFORCER",
      "DALAN OBEROS",
      "GURI",
      "PRINCE XIZOR",
    ],
  },
  {
    id: "scumandvillainy-tridentclassassaultship",
    title: "TRIDENT-CLASS ASSAULT SHIP",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "TRIDENTCLASSASSAULTSHIP",
      "LAWLESSPIRATES",
      "LAWLESSPIRATES",
      "LAWLESSPIRATES",
      "LAWLESSPIRATES",
    ],
  },
  {
    id: "scumandvillainy-yv666lightfreighter",
    title: "YV-666 LIGHT FREIGHTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "YV666LIGHTFREIGHTER",
      "BOSSK",
      "BOSSK",
      "LATTS RAZZI",
      "LATTS RAZZI",
      "MORALO EVAL",
      "MORALO EVAL",
      "TRANDOSHAN SLAVER",
      "TRANDOSHAN SLAVER",
      "TRANDOSHAN SLAVER",
    ],
  },
  {
    id: "scumandvillainy-z95af4headhunter",
    title: "Z-95-AF4 HEADHUNTER",
    category: ["SHIP", "SCUMANDVILLAINY"],
    tags: [
      "Z95AF4HEADHUNTER",
      "BINAYRE PIRATE",
      "BINAYRE PIRATE",
      "BINAYRE PIRATE",
      "BLACK SUN SOLDIER",
      "BLACK SUN SOLDIER",
      "BLACK SUN SOLDIER",
      "BLACK SUN SOLDIER",
      "KAA'TO LEEACHOS",
      "KAA'TO LEEACHOS",
      "N'DRU SUHLAK",
      "N'DRU SUHLAK",
      "NASHTAH PUP",
      "NASHTAH PUP",
      "NASHTAH PUP",
      "BOSSK",
      "BOSSK",
    ],
  },
  {
    id: "galacticempire-alphaclassstarwing",
    title: "ALPHA-CLASS STAR WING",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "ALPHACLASSSTARWING",
      "LIEUTENANT KARSABI",
      "MAJOR VYNDER",
      "NU SQUADRON PILOT",
      "RHO SQUADRON PILOT",
    ],
  },
  {
    id: "galacticempire-gauntletfighter",
    title: "GAUNTLETFIGHTER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "GAUNTLETFIGHTER",
      "CAPTAINHARK",
      "GARSAXON",
      "IMPERIALSUPERCOMMANDO",
    ],
  },
  {
    id: "galacticempire-gozanticlasscruiser",
    title: "GOZANTI-CLASS CRUISER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: ["GOZANTICLASSCRUISER", "OUTER RIM GARRISON", "OUTER RIM GARRISON"],
  },
  {
    id: "galacticempire-lambdaclasst4ashuttle",
    title: "LAMBDA-CLASS T-4A SHUTTLE",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "LAMBDACLASST4ASHUTTLE",
      "CAPTAIN KAGI",
      "COLONEL JENDON",
      "LIEUTENANT SAI",
      "OMICRON GROUP PILOT",
    ],
  },
  {
    id: "galacticempire-raiderclasscorvette",
    title: "RAIDER-CLASS CORVETTE",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: ["RAIDERCLASSCORVETTE", "OUTER RIM PATROL", "OUTER RIM PATROL"],
  },
  {
    id: "galacticempire-tieadvancedv1",
    title: "TIE ADVANCED V1",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEADVANCEDV1",
      "BARON OF THE EMPIRE",
      "BARON OF THE EMPIRE",
      "BARON OF THE EMPIRE",
      "GRAND INQUISITOR",
      "GRAND INQUISITOR",
      "INQUISITOR",
      "INQUISITOR",
      "INQUISITOR",
      "SEVENTH SISTER",
      "SEVENTH SISTER",
      "FIFTH BROTHER",
    ],
  },
  {
    id: "galacticempire-tieadvancedx1",
    title: "TIE ADVANCED X1",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEADVANCEDX1",
      "DARTH VADER",
      "MAAREK STELE",
      "STORM SQUADRON ACE",
      "TEMPEST SQUADRON PILOT",
      "VED FOSLO",
      "ZERTIK STROM",
    ],
  },
  {
    id: "galacticempire-tieininterceptor",
    title: "TIE/IN INTERCEPTOR",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEININTERCEPTOR",
      "ALPHA SQUADRON PILOT",
      "ALPHA SQUADRON PILOT",
      "ALPHA SQUADRON PILOT",
      "ALPHA SQUADRON PILOT",
      "ALPHA SQUADRON PILOT",
      "SABER SQUADRON ACE",
      "SABER SQUADRON ACE",
      "SABER SQUADRON ACE",
      "SOONTIR FEL",
      "SOONTIR FEL",
      "TURR PHENNIR",
      "TURR PHENNIR",
      "CIENA REE",
      "GIDEON HASK",
      "VULT SKERRIS",
      "COMMANDANT GORAN",
      "LIEUTENANT LORRIR",
      "NASH WINDRIDER",
    ],
  },
  {
    id: "galacticempire-tiereaper",
    title: "TIE REAPER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEREAPER",
      "“VIZIER”",
      "CAPTAIN FEROPH",
      "MAJOR VERMEIL",
      "SCARIF BASE PILOT",
    ],
  },
  {
    id: "galacticempire-tieddefender",
    title: "TIE/D DEFENDER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEDDEFENDER",
      "COLONEL VESSERY",
      "COLONEL VESSERY",
      "COUNTESS RYAD",
      "COUNTESS RYAD",
      "DELTA SQUADRON PILOT",
      "DELTA SQUADRON PILOT",
      "DELTA SQUADRON PILOT",
      "ONYX SQUADRON ACE",
      "ONYX SQUADRON ACE",
      "ONYX SQUADRON ACE",
      "ONYX SQUADRON ACE",
      "REXLER BRATH",
      "REXLER BRATH",
      "VULT SKERRIS",
      "DARTH VADER",
      "CAPTAIN DOBBS",
    ],
  },
  {
    id: "galacticempire-tieagaggressor",
    title: "TIE/AG AGGRESSOR",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEAGAGGRESSOR",
      "“DOUBLE EDGE”",
      "LIEUTENANT KESTAL",
      "ONYX SQUADRON SCOUT",
      "SIENAR SPECIALIST",
    ],
  },
  {
    id: "galacticempire-tiecapunisher",
    title: "TIE/CA PUNISHER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIECAPUNISHER",
      "“DEATHRAIN”",
      "“REDLINE”",
      "CUTLASS SQUADRON PILOT",
      "CUTLASS SQUADRON PILOT",
    ],
  },
  {
    id: "galacticempire-tielnfighter",
    title: "TIE/LN FIGHTER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIELNFIGHTER",
      "“HOWLRUNNER”",
      "“NIGHT BEAST”",
      "“SCOURGE” SKUTU",
      "“WAMPA”",
      "ACADEMY PILOT",
      "ACADEMY PILOT",
      "ACADEMY PILOT",
      "BLACK SQUADRON ACE",
      "BLACK SQUADRON ACE",
      "BLACK SQUADRON ACE",
      "BLACK SQUADRON ACE",
      "DEL MEEKO",
      "GIDEON HASK",
      "IDEN VERSIO",
      "IDEN VERSIO",
      "OBSIDIAN SQUADRON PILOT",
      "OBSIDIAN SQUADRON PILOT",
      "OBSIDIAN SQUADRON PILOT",
      "SEYN MARANA",
      "VALEN RUDOR",
      "ISB JINGOIST",
      "ISB JINGOIST",
      "MOFF GIDEON",
      "MOFF GIDEON",
    ],
  },
  {
    id: "galacticempire-tiephphantom",
    title: "TIE/PH PHANTOM",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIEPHPHANTOM",
      "“ECHO”",
      "“WHISPER”",
      "IMDAAR TEST PILOT",
      "SIGMA SQUADRON ACE",
    ],
  },
  {
    id: "galacticempire-tiesabomber",
    title: "TIE/SA BOMBER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIESABOMBER",
      "“DEATHFIRE”",
      "CAPTAIN JONUS",
      "GAMMA SQUADRON ACE",
      "MAJOR RHYMER",
      "SCIMITAR SQUADRON PILOT",
      "SCIMITAR SQUADRON PILOT",
      "TOMAX BREN",
    ],
  },
  {
    id: "galacticempire-tieskstriker",
    title: "TIE/SK STRIKER",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIESKSTRIKER",
      "“COUNTDOWN”",
      "“COUNTDOWN”",
      "“DUCHESS”",
      "“DUCHESS”",
      "“PURE SABACC”",
      "“PURE SABACC”",
      "BLACK SQUADRON SCOUT",
      "BLACK SQUADRON SCOUT",
      "BLACK SQUADRON SCOUT",
      "PLANETARY SENTINEL",
      "PLANETARY SENTINEL",
      "PLANETARY SENTINEL",
      "PLANETARY SENTINEL",
      "“VAGABOND”",
    ],
  },
  {
    id: "galacticempire-vt49decimator",
    title: "VT-49 DECIMATOR",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "VT49DECIMATOR",
      "CAPTAIN OICUNN",
      "CAPTAIN OICUNN",
      "PATROL LEADER",
      "PATROL LEADER",
      "PATROL LEADER",
      "PATROL LEADER",
      "REAR ADMIRAL CHIRANEAU",
      "REAR ADMIRAL CHIRANEAU",
      "MORNA KEE",
    ],
  },
  {
    id: "galacticempire-tierbheavy",
    title: "TIE/RB HEAVY",
    category: ["SHIP", "GALACTICEMPIRE"],
    tags: [
      "TIERBHEAVY",
      "CARIDA ACADEMY CADET",
      "CARIDA ACADEMY CADET",
      "ONYX SQUADRON SENTRY",
      "ONYX SQUADRON SENTRY",
      "“RAMPAGE”",
      "“RAMPAGE”",
      "LYTTAN DREE",
      "LYTTAN DREE",
    ],
  },
  {
    id: "resistance-gr75mediumtransport",
    title: "GR-75 MEDIUM TRANSPORT",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "GR75MEDIUMTRANSPORT",
      "NEW REPUBLIC VOLUNTEERS",
      "NEW REPUBLIC VOLUNTEERS",
    ],
  },
  {
    id: "resistance-mg100starfortress",
    title: "MG-100 STARFORTRESS",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "MG100STARFORTRESS",
      "COBALT SQUADRON BOMBER",
      "COBALT SQUADRON BOMBER",
      "CAT",
      "VENNIE",
      "BEN TEENE",
      "EDON KAPPEHL",
      "FINCH DALLOW",
      "PAIGE TICO",
    ],
  },
  {
    id: "resistance-scavengedyt1300",
    title: "SCAVENGED YT-1300",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "SCAVENGEDYT1300",
      "RESISTANCE SYMPATHIZER",
      "CHEWBACCA",
      "HAN SOLO",
      "REY",
    ],
  },
  {
    id: "resistance-rz2awing",
    title: "RZ-2 A-WING",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "RZ2AWING",
      "L'ULO L'AMPAR",
      "TALLISSAN LINTRA",
      "ZARI BANGEL",
      "GREER SONNEL",
      "GREER SONNEL",
      "GREEN SQUADRON EXPERT",
      "GREEN SQUADRON EXPERT",
      "BLUE SQUADRON RECRUIT",
      "BLUE SQUADRON RECRUIT",
      "BLUE SQUADRON RECRUIT",
      "ZIZI TLO",
      "RONITH BLARIO",
      "MERL COBBEN",
      "SURALINDA JAVOS",
      "WROBIE TYCE",
      "SEFTIN VANIK",
    ],
  },
  {
    id: "resistance-t70xwing",
    title: "T-70 X-WING",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "T70XWING",
      "POE DAMERON",
      "POE DAMERON",
      "BLUE SQUADRON ROOKIE",
      "BLUE SQUADRON ROOKIE",
      "RED SQUADRON EXPERT",
      "RED SQUADRON EXPERT",
      "BLACK SQUADRON ACE",
      "BLACK SQUADRON ACE",
      "ELLO ASTY",
      "JOPH SEASTRIKER",
      "KARE KUN",
      "LIEUTENANT BASTIAN",
      "NIEN NUNB",
      "JAYCRIS TUBBS",
      "JESSIKA PAVA",
      "TEMMIN WEXLEY",
      "TEMMIN WEXLEY",
      "C'AI THRENALLI",
      "NIMI CHEREEN",
    ],
  },
  {
    id: "resistance-resistancetransport",
    title: "RESISTANCE TRANSPORT",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "RESISTANCETRANSPORT",
      "COVA NELL",
      "PAMMICH NERRO GOODE",
      "NODIN CHAVDRI",
      "LOGISTICS DIVISION PILOT",
    ],
  },
  {
    id: "resistance-resistancetransportpod",
    title: "RESISTANCE TRANSPORT POD",
    category: ["SHIP", "RESISTANCE"],
    tags: ["RESISTANCETRANSPORTPOD", "BB-8", "ROSE TICO", "VI MORADI", "FINN"],
  },
  {
    id: "resistance-fireball",
    title: "FIREBALL",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "FIREBALL",
      "COLOSSUS STATION MECHANIC",
      "JAREK YEAGER",
      "KAZUDA XIONO",
      "R1-J5",
    ],
  },
  {
    id: "resistance-btanr2ywing",
    title: "BTANR2YWING",
    category: ["SHIP", "RESISTANCE"],
    tags: [
      "BTANR2YWING",
      "ZORIIBLISS",
      "TEZANASZ",
      "WILSATESHLO",
      "SHASAZARO",
      "LEGAFOSSANG",
      "AFTABACKBAR",
      "CORUSKAPELLIM",
      "CAITHRENALLI-BTANR2YWING",
      "NEWREPUBLICPATROL",
      "KIJIMISPICERUNNER",
    ],
  },
  {
    id: "firstorder-gozanticlasscruiser",
    title: "GOZANTI-CLASS CRUISER",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "GOZANTICLASSCRUISER",
      "FIRST ORDER SYMPATHIZERS",
      "FIRST ORDER SYMPATHIZERS",
    ],
  },
  {
    id: "firstorder-raiderclasscorvette",
    title: "RAIDER-CLASS CORVETTE",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "RAIDERCLASSCORVETTE",
      "FIRST ORDER COLLABORATORS",
      "FIRST ORDER COLLABORATORS",
    ],
  },
  {
    id: "firstorder-tiebainterceptor",
    title: "TIE/BA INTERCEPTOR",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIEBAINTERCEPTOR",
      "MAJOR VONREG",
      "“HOLO”",
      "“EMBER”",
      "FIRST ORDER PROVOCATEUR",
    ],
  },
  {
    id: "firstorder-tiefofighter",
    title: "TIE/FO FIGHTER",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIEFOFIGHTER",
      "“MIDNIGHT”",
      "COMMANDER MALARUS (PERFECTED)",
      "“SCORCH”",
      "“STATIC”",
      "“LONGSHOT”",
      "OMEGA SQUADRON ACE",
      "“MUSE”",
      "TN-3465",
      "ZETA SQUADRON PILOT",
      "EPSILON SQUADRON CADET",
      "LIEUTENANT RIVAS",
      "“NULL”",
    ],
  },
  {
    id: "firstorder-tiesffighter",
    title: "TIE/SF FIGHTER",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIESFFIGHTER",
      "“QUICKDRAW”",
      "“BACKDRAFT”",
      "OMEGA SQUADRON EXPERT",
      "ZETA SQUADRON SURVIVOR",
      "ZETA SQUADRON SURVIVOR",
      "LIEUTENANT LEHUSE",
      "CAPTAIN PHASMA",
    ],
  },
  {
    id: "firstorder-tievnsilencer",
    title: "TIE/VN SILENCER",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIEVNSILENCER",
      "“BLACKOUT”",
      "“BLACKOUT”",
      "KYLO REN",
      "FIRST ORDER TEST PILOT",
      "FIRST ORDER TEST PILOT",
      "“RECOIL”",
      "“AVENGER”",
      "SIENAR-JAEMUS ENGINEER",
      "SIENAR-JAEMUS ENGINEER",
      "“RUSH”",
    ],
  },
  {
    id: "firstorder-upsilonclassshuttle",
    title: "UPSILON-CLASS COMMAND SHUTTLE",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "UPSILONCLASSSHUTTLE",
      "LIEUTENANT DORMITZ",
      "MAJOR STRIDAN",
      "PETTY OFFICER THANISSON",
      "STARKILLER BASE PILOT",
      "LIEUTENANT TAVSON",
      "CAPTAIN CARDINAL",
    ],
  },
  {
    id: "firstorder-xiclasslightshuttle",
    title: "XICLASSLIGHTSHUTTLE",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "XICLASSLIGHTSHUTTLE",
      "AGENT TEREX",
      "COMMANDER MALARUS",
      "FIRST ORDER COURIER",
      "GIDEON HASK",
    ],
  },
  {
    id: "firstorder-tiesebomber",
    title: "TIESEBOMBER",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIESEBOMBER",
      "BREACH",
      "SCORCH-TIESEBOMBER",
      "DREAD",
      "GRUDGE",
      "FIRSTORDERCADET",
      "SIENARJAEMUSTESTPILOT",
    ],
  },
  {
    id: "firstorder-tiewiwhispermodifiedinterceptor",
    title: "TIEWIWHISPERMODIFIEDINTERCEPTOR",
    category: ["SHIP", "FIRSTORDER"],
    tags: [
      "TIEWIWHISPERMODIFIEDINTERCEPTOR",
      "KYLOREN-TIEWIWHISPERMODIFIEDINTERCEPTOR",
      "WRATH",
      "NIGHTFALL",
      "WHIRLWIND",
      "709THLEGIONACE",
      "REDFURYZEALOT",
    ],
  },
  {
    id: "separatistalliance-vultureclassdroidfighter",
    title: "VULTURE-CLASS DROID FIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "VULTURECLASSDROIDFIGHTER",
      "TRADE FEDERATION DRONE",
      "PRECISE HUNTER",
      "HAOR CHALL PROTOTYPE",
      "HAOR CHALL PROTOTYPE",
      "DFS-081",
      "SEPARATIST DRONE",
      "DFS-311",
    ],
  },
  {
    id: "separatistalliance-croccruiser",
    title: "C-ROC CRUISER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: ["CROCCRUISER", "SEPARATIST PRIVATEERS", "SEPARATIST PRIVATEERS"],
  },
  {
    id: "separatistalliance-belbullab22starfighter",
    title: "BELBULLAB-22 STARFIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "BELBULLAB22STARFIGHTER",
      "GENERAL GRIEVOUS",
      "WAT TAMBOR",
      "FEETHAN OTTRAW AUTOPILOT",
      "CAPTAIN SEAR",
      "SKAKOAN ACE",
    ],
  },
  {
    id: "separatistalliance-sithinfiltrator",
    title: "SITH INFILTRATOR",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "SITHINFILTRATOR",
      "DARTH MAUL",
      "COUNT DOOKU",
      "DARK COURIER",
      "0-66",
    ],
  },
  {
    id: "separatistalliance-hyenaclassdroidbomber",
    title: "HYENA-CLASS DROID BOMBER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "HYENACLASSDROIDBOMBER",
      "TECHNO UNION BOMBER",
      "BOMBARDMENT DRONE",
      "DBS-404",
      "BAKTOID PROTOTYPE",
      "SEPARATIST BOMBER",
      "DBS-32C",
    ],
  },
  {
    id: "separatistalliance-nantexclassstarfighter",
    title: "NANTEX-CLASS STARFIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "NANTEXCLASSSTARFIGHTER",
      "STALGASIN HIVE GUARD",
      "SUN FAC",
      "BERWER KRET",
      "CHERTEK",
      "GORGOL",
      "PETRANAKI ARENA ACE",
    ],
  },
  {
    id: "separatistalliance-droidtrifighter",
    title: "DROIDTRIFIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "DROIDTRIFIGHTER",
      "DIS-T81",
      "PHLAC-ARPHOCC PROTOTYPE",
      "FEARSOME PREDATOR",
      "DIS-347",
      "SEPARATIST INTERCEPTOR",
      "COLICOID INTERCEPTOR",
    ],
  },
  {
    id: "separatistalliance-hmpdroidgunship",
    title: "HMPDROIDGUNSHIP",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "HMPDROIDGUNSHIP",
      "DGS-047",
      "BAKTOID DRONE",
      "GEONOSIAN PROTOTYPE",
      "DGS-286",
      "ONDERON OPPRESSOR",
      "SEPARATIST PREDATOR",
    ],
  },
  {
    id: "separatistalliance-tridentclassassaultship",
    title: "TRIDENT-CLASS ASSAULT SHIP",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "TRIDENTCLASSASSAULTSHIP",
      "COLICOID DESTROYER",
      "COLICOID DESTROYER",
      "COLICOID DESTROYER",
      "COLICOID DESTROYER",
      "COLICOID DESTROYER",
      "COLICOID DESTROYER",
    ],
  },
  {
    id: "separatistalliance-firesprayclasspatrolcraft",
    title: "FIRESPRAY-CLASS PATROL CRAFT",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "FIRESPRAYCLASSPATROLCRAFT",
      "JANGO FETT",
      "ZAM WESELL",
      "BOBA FETT",
      "SEPARATIST RACKETEER",
    ],
  },
  {
    id: "separatistalliance-rogueclassstarfighter",
    title: "ROGUECLASSSTARFIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "ROGUECLASSSTARFIGHTER",
      "CADBANE-SEPARATISTALLIANCE",
      "IG101",
      "MAGNAGUARDEXECUTIONER",
      "MAGNAGUARDPROTECTOR",
      "IG102",
      "IG111",
    ],
  },
  {
    id: "separatistalliance-gauntletfighter",
    title: "GAUNTLETFIGHTER",
    category: ["SHIP", "SEPARATISTALLIANCE"],
    tags: [
      "GAUNTLETFIGHTER",
      "BOKATANKRYZE-SEPARATISTALLIANCE",
      "PREVIZSLA",
      "DEATHWATCHWARRIOR",
    ],
  },
  {
    id: "galacticrepublic-arc170starfighter",
    title: "ARC-170 STARFIGHTER",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "ARC170STARFIGHTER",
      "“SINKER”",
      "“JAG”",
      "“ODD BALL”",
      "“WOLFFE”",
      "104TH BATTALION PILOT",
      "SQUAD SEVEN VETERAN",
    ],
  },
  {
    id: "galacticrepublic-delta7aethersprite",
    title: "DELTA-7 AETHERSPRITE",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "DELTA7AETHERSPRITE",
      "JEDI KNIGHT",
      "OBI-WAN KENOBI",
      "PLO KOON",
      "SAESEE TIIN",
      "MACE WINDU",
      "ANAKIN SKYWALKER",
      "AHSOKA TANO",
      "BARRISS OFFEE",
      "LUMINARA UNDULI",
    ],
  },
  {
    id: "galacticrepublic-cr90corelliancorvette",
    title: "CR90 CORELLIAN CORVETTE",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: ["CR90CORELLIANCORVETTE", "REPUBLIC JUDICIARY", "REPUBLIC JUDICIARY"],
  },
  {
    id: "galacticrepublic-v19torrentstarfighter",
    title: "V-19 TORRENT STARFIGHTER",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "V19TORRENTSTARFIGHTER",
      "“KICKBACK”",
      "“ODD BALL”",
      "“SWOOP”",
      "“AXE”",
      "“TUCKER”",
      "BLUE SQUADRON PROTECTOR",
      "GOLD SQUADRON TROOPER",
    ],
  },
  {
    id: "galacticrepublic-nabooroyaln1starfighter",
    title: "NABOO ROYAL N-1 STARFIGHTER",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "NABOOROYALN1STARFIGHTER",
      "ANAKIN SKYWALKER",
      "RIC OLIÉ",
      "PADMÉ AMIDALA",
      "DINEÉ ELLBERGER",
      "BRAVO FLIGHT OFFICER",
      "NABOO HANDMAIDEN",
    ],
  },
  {
    id: "galacticrepublic-btlbywing",
    title: "BTL-B Y-WING",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "BTLBYWING",
      "SHADOW SQUADRON VETERAN",
      "SHADOW SQUADRON VETERAN",
      "ANAKIN SKYWALKER",
      "ANAKIN SKYWALKER",
      "R2-D2",
      "R2-D2",
      "“ODD BALL”",
      "“ODD BALL”",
      "“MATCHSTICK”",
      "“MATCHSTICK”",
      "“BROADSIDE”",
      "“BROADSIDE”",
      "“GOJI”",
      "“GOJI”",
      "RED SQUADRON BOMBER",
      "RED SQUADRON BOMBER",
    ],
  },
  {
    id: "galacticrepublic-eta2actis",
    title: "ETA2ACTIS",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "ETA2ACTIS",
      "ANAKIN SKYWALKER",
      "OBI-WAN KENOBI",
      "AAYLA SECURA",
      "SHAAK TI",
      "JEDI GENERAL",
      "YODA",
    ],
  },
  {
    id: "galacticrepublic-gauntletfighter",
    title: "GAUNTLETFIGHTER",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: ["GAUNTLETFIGHTER", "BOKATANKRYZE", "NITEOWLLIBERATOR"],
  },
  {
    id: "galacticrepublic-laatigunship",
    title: "LAATIGUNSHIP",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "LAATIGUNSHIP",
      "“HAWK”",
      "“HOUND”",
      "“WARTHOG”",
      "212TH BATTALION PILOT",
    ],
  },
  {
    id: "galacticrepublic-nimbusclassvwing",
    title: "NIMBUSCLASSVWING",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "NIMBUSCLASSVWING",
      "WILHUFF TARKIN",
      "“ODD BALL”",
      "“CONTRAIL”",
      "“KLICK”",
      "SHADOW SQUADRON ESCORT",
      "LOYALIST VOLUNTEER",
    ],
  },
  {
    id: "galacticrepublic-syliureclasshyperspacering",
    title: "SYLIURECLASSHYPERSPACERING",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: ["SYLIURECLASSHYPERSPACERING", "TRANSGALMEGCONTROLLINK"],
  },
  {
    id: "galacticrepublic-clonez95headhunter",
    title: "CLONEZ95HEADHUNTER",
    category: ["SHIP", "GALACTICREPUBLIC"],
    tags: [
      "CLONEZ95HEADHUNTER",
      "KILLER",
      "DRIFT",
      "BOOST",
      "STUB",
      "KNACK",
      "HAWK-CLONEZ95HEADHUNTER",
      "7THSKYCORPSPILOT",
      "REAPERSQUADRONSCOUT",
      "SLIDER",
      "WARTHOG-CLONEZ95HEADHUNTER",
    ],
  },
];
