import "../../icons.css";

const icons = {
    Straight: () => <i className='font-straight'></i>,
    Boost: () => <i className="font-boost"></i>,
    Lock: () => <i className="font-lock"></i>,
    Forcepower: () => <i className="font-forcepower"></i>,
    Focus: () => <i className="font-focus"></i>,
    Title: () => <i className='font-title'></i>,
    Slam: () => <i className='font-slam'></i>,
    Jam: () => <i className="font-jam"></i>,
    Reload: () => <i className='font-reload'></i>,
    Reinforce: () => <i className="font-reinforce"></i>,
    Cannon: () => <i className="font-cannon"></i>,
    Torpedo: () => <i className="font-torpedo"></i>,
    Missile: () => <i className="font-missile"></i>,
    FrontArc: () => <i className="font-frontarc"></i>,
    LeftArc: () => <i className="font-leftarc"></i>,
    RightArc: () => <i className="font-rightarc"></i>,
    RearArc: () => <i className="font-reararc"></i>,
    BullsEyeArc: () => <i className="font-bullseyearc"></i>,
    FullFrontArc: () => <i className="font-fullfrontarc"></i>,
    FullRearArc: () => <i className="font-fullreararc"></i>,
    SingleTurretArc: () => <i className="font-singleturretarc"></i>,
    DoubleTurretArc: () => <i className="font-doubleturretarc"></i>,
    Rotate: () => <i className="font-rotatearc"></i>,
    Evade: () => <i className="font-evade"></i>,
    Hit: () => <i className="font-hit"></i>,
    Crit: () => <i className="font-crit"></i>,
    CriticalHit: () => <i className="font-crit"></i>,
    BarrelRoll: () => <i className="font-barrelroll"></i>,
    Calculate: () => <i className='font-calculate'></i>,
    Charge: () => <i className="font-charge"></i>,
    Shield: () => <i className="font-shield"></i>,
    Energy: () => <i className="font-energy"></i>,
    Cloak: () => <i className="font-cloak"></i>,
    RotateArc: () => <i className="font-rotatearc uppercase"></i>,
    LeftBank: () => <i className='font-bankleft'></i>,
    RightBank: () => <i className="font-bankright"></i>,
    BankLeft: () => <i className='font-bankleft'></i>,
    BankRight: () => <i className="font-bankright"></i>,
    LeftTurn: () => <i className="font-turnleft"></i>,
    TurnLeft: () => <i className="font-turnleft"></i>,
    RightTurn: () => <i className='font-turnright'></i>,
    TurnRight: () => <i className='font-turnright'></i>,
    KTurn: () => <i className='font-kturn'></i>,
    TallonRight: () => <i className='font-trollright'></i>,
    TallonLeft: () => <i className='font-trollleft'></i>,
    SegnorLeft: () => <i className='font-sloopleft'></i>,
    SegnorRight: () => <i className='font-sloopright'></i>,
    Stationary: () => <i className='font-stop'></i>,
    RStraight: () => <i className='font-reversestraight'></i>,
    RBankRight: () => <i className='font-reversebankright'></i>,
    RBankLeft: () => <i className='font-reversebankleft'></i>,
    Device: () => <i className='font-device'></i>,
    Crew: () => <i className='font-crew'></i>,
    Coordinate: () => <i className="font-coordinate"></i>,
    Linked: () => <i className='font-linked'></i>,
    TacticalRelay: () => <i className='font-tacticalrelay'></i>,
    Astromech: () => <i className="font-astromech"></i>,
    Configuration: () => <i className='font-config'></i>,
    Gunner: () => <i className='font-gunner'></i>,
    Illicit: () => <i className="font-illicit"></i>,
    ForcePowerU: () => <i className="font-forcepoweru"></i>,
    Modification: () => <i className='font-modification'></i>,
    Sensor: () => <i className='font-sensor'></i>,
    Talent: () => <i className='font-talent'></i>,
    Tech: () => <i className='font-tech'></i>,
    Turret: () => <i className='font-turret'></i>,
    RangeBonusIndicator: () => <i className='font-rangebonusindicator'></i>,
    Hardpoint: () => <i className='font-hardpoint'></i>,
    Point: () => <i className='font-point'></i>,
    Cargo: () => <i className='font-cargo'></i>,
    Command: () => <i className='font-command'></i>,
    Team: () => <i className='font-team'></i>
}

export type IconNames = keyof typeof icons;
(icons as unknown as (IconNames & { BullseyeArc: () => JSX.Element; })).BullseyeArc = icons.BullsEyeArc;



export default icons;